name: demo

plugins:
  - name: solidity
    version: 0.7.0

dependencies:
  - name: smartcontractkit
    github: smartcontractkit/chainlink-brownie-contracts
    version: 0.8.0
  - name: solmate
    github: transmissions11/solmate
    ref: "v6"
    config_overrides:
      contracts_folder: src
      compile:
        exclude: 
          - ./test/utils/*


solidity:
  version: 0.8.23
  import_remapping:
    - "@chainlink/contracts=smartcontractkit/0.8.0"
    - "@solmate=solmate/6"
